// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsF63AvUMpJVWn85jJ2KLgM742AK_optI',
    appId: '1:1078496718491:web:4b06c8a66a8b02b52aa03e',
    messagingSenderId: '1078496718491',
    projectId: 'mesclainvestluis',
    authDomain: 'mesclainvestluis.firebaseapp.com',
    storageBucket: 'mesclainvestluis.firebasestorage.app',
    measurementId: 'G-NCCWS1FEPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2EVlZAZuf2zeOKHS8Gorq2r2X_JJ-dxk',
    appId: '1:1078496718491:android:ff9c37c8e75a59a42aa03e',
    messagingSenderId: '1078496718491',
    projectId: 'mesclainvestluis',
    storageBucket: 'mesclainvestluis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxo0S76FmOPlZEn4HAflf1NC9hmMLP2N4',
    appId: '1:1078496718491:ios:70ebd95d8c27209d2aa03e',
    messagingSenderId: '1078496718491',
    projectId: 'mesclainvestluis',
    storageBucket: 'mesclainvestluis.firebasestorage.app',
    iosBundleId: 'com.example.mesclaInvest',
  );
}
